### PR TITLE
Prevent user from editing polyline to have intersecting edges

### PR DESCRIPTION
**Pull request by Gerg**

### CODE REVIEW

**Comment by Gerg** [comment]
@chasemgray bump

**Comment by chasemgray** [comment]
Are the Leaflet.Draw tests failing still? I think we should make sure we don't break the existing tests at least. If not, then lgtm.

**Comment by Gerg** [comment]
The same tests are failing as the sha before this PR.

**Comment by chasemgray** [comment]
:( ok. we'll merge it I suppose.

old_disappointed_lady

**Comment by Gerg** [comment]
If you guys are going to continue to use/edit the fork of Leaflet.Draw, it might make sense to prioritize some engineering time to fix things up. Not sure how often we expect to touch this.

**Pull request merged**
